# Generated by Django 3.2.4 on 2021-06-09 09:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('food_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('ingredient', models.TextField()),
                ('time_prep', models.CharField(max_length=50)),
                ('process', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.profile')),
            ],
        ),
    ]
